### ISSUE TITLE
Separate the code to run in different processes

### ISSUE THREAD

**Issue by ineiti** [dedis/student_24_mino_libp2p#2]
Get it to run on two computers
- have two arguments, only one of them is given at any one time:
- `--create` - creates a random address and prints it
- `--connect` - takes a local and a remote address and pings the remote and shows the locally received pings
- exchange addresses over slack
- run each node on a separate computer with the address of the other computer
- bonus point: use more than two nodes, so give more than two addresses in `--connect`

Running 3 nodes to get the addresses:

```
s1# ./node --create
Your address is: something1
s2# ./node --create
Your address is: something2
s3# ./node --create
Your address is: something3
```

Running 3 nodes to exchange pings:

```
s1# ./node --connect something1 something2 something3
Starting to ping
s2# ./node --connect something2 something1 something3
Starting to ping
s3# ./node --connect something3 something1 something2
```

**Comment by XioZ** [comment]
assumption: every node is started 1s apart, no need to check whether already exists a stream between itself and a neighbor, directly attempt to connect to each neighbor on startup, stop and just listen if fails.

**Comment by XioZ** [comment]
cases where both nodes initiate a connection to each other at the same time and both successfully establish a connection is still possible, when we don't control the timing of node start up. to be handled in future

**Comment by XioZ** [comment]
there are cases where A wants to connect to B but B doesn't want to connect to A. i.e. not every pair of nodes want to connect with each other, but connection still needs to be established when it's one way

**Comment by ineiti** [comment]
This works now!
